### ISSUE TITLE
I'm probably misunderstanding asyncio.sleep

### ISSUE THREAD

**Issue by kootenpv** [kespindler/albatross#7]
If having trouble with the line:

```
await asyncio.sleep(0.1)
```

I was under the impression that if I would send 1000 requests really fast (asynchronously), then given that you could handle 1000 requests, they would all be returned in 0.1 second later + overhead + PC bounds like CPU/mem.

But when I run 1000 requests (I'll post scripts below), then it takes 1 minute and 49 seconds, meaning  over 100 seconds -> synchronous?

Any idea what's wrong with my thoughts/code?
## server.py

``` python
import asyncio
from albatross import Server

class Handler:
    async def on_get(self, req, res):
        await asyncio.sleep(0.1)
        res.write('Hello {}'.format(req.args['name']))

app = Server()
app.add_route('/(?P<name>[a-z]+)', Handler())
app.serve()
```
## client.py <-- (red flag, do not use)

``` python
import asyncio
import requests

@asyncio.coroutine
def main():
    loop = asyncio.get_event_loop()
    for i in range(1000):
        future1 = loop.run_in_executor(None, requests.get, 'http://localhost:8000/name')
        response1 = yield from future1
    print(response1.text)

loop = asyncio.get_event_loop()
loop.run_until_complete(main())

```

**Comment by kootenpv** [comment]
Client code is wrong. I don't know where I copy pasted that snippet from, but this one works a lot better ;) **1.667** seconds!

## client.py

```
#!/usr/local/bin/python3.5
import asyncio
from aiohttp import ClientSession

url = 'http://localhost:8000/name'

async def hello():
    async with ClientSession() as session:
        async with session.get(url) as response:
            response = await response.read()

loop = asyncio.get_event_loop()

tasks = []
for i in range(1000):
    task = asyncio.ensure_future(hello())
    tasks.append(task)
loop.run_until_complete(asyncio.wait(tasks))

```

**Comment by kespindler** [comment]
:) Thanks for verifying this and posting the client code. I'm a bit surprised you're still getting 0.353 seconds, but at least that's the right order of magnitude. On this note, I would like to make an actual benchmark of albatross, tornado, and aiohttp at some point. This is a good starting point.

**Comment by kootenpv** [comment]
The previous of 0.353 was based on only 1 request, 1.667s is for 1000 requests (updated in previous comment).

**Comment by kootenpv** [comment]
Strangely, synchronous flask took **1.535** seconds on this....

**Comment by kootenpv** [comment]
Synchronous flask took 1.535s without sleeps.

**Comment by kespindler** [comment]
Odd. I'll dig into this later tonight.

**Comment by kootenpv** [comment]
Btw, the most awesome "client" testing is `ab -c 12 -n 120 127.0.0.1:8000/name` (Apache Benchmark tool)

**Comment by kespindler** [comment]
If you add some print statements, you can see that the sleep is behaving correctly.

``` python
# server.py
import asyncio
from albatross import Server

class Handler:
    async def on_get(self, req, res):
        print('sleeping')
        await asyncio.sleep(0.1)
        print('responding')
        res.write('Hello {}'.format(req.args['name']))

app = Server()
app.add_route('/(?P<name>[a-z]+)', Handler())
app.serve()
```

``` python
# client.py
#!/usr/local/bin/python3.5
import asyncio
from aiohttp import ClientSession
from time import time

url = 'http://localhost:8000/name'

async def hello():
    async with ClientSession() as session:
        print('getting')
        start = time()
        async with session.get(url) as response:
            response = await response.read()
            dur = time() - start
            print('read response, took %.5f' % dur)



loop = asyncio.get_event_loop()

tasks = []
for i in range(10):
    task = asyncio.ensure_future(hello())
    tasks.append(task)
loop.run_until_complete(asyncio.wait(tasks))
```

I did some early one-off tests comparing the performance of tornado and albatross, and albatross came out about 10% ahead. Definitely should have standard benchmarks though.

And to confirm, the ~1.5s with Flask was _without_ the sleep, correct? With the sleep your perf will be tanked on flask.

**Comment by kootenpv** [comment]
> And to confirm, the ~1.5s with Flask was without the sleep, correct?
> 
> > Synchronous flask took 1.535s without sleeps.

Looking forward to the benchmarks :) Though in reality, convenience is more important I'd guess.

**Comment by kespindler** [comment]
@kootenpv Did some preliminary benchmarks this weekend, which are available in the `bench/` folder if you want to poke around. I'm just running with a bash script for now- better ways to run it are welcome.

Benchmarks can be run with

```
cd bench && ./benchmark.sh
```

Highlights:
- on a "hello" (just echoing hello world) benchmark, albatross is about 2x as fast as tornado and aiohttp. Expected, as I'm generally doing a lot less work. (35ms albatross, 58ms tornado, 59ms aiohttp)
- on a "form" benchmark request  (36kB URL encoded body), aiohttp and albatross are neck-to-neck, while tornado is about 50% slower than the other two.

From engineering the tests, it looks a surprising amount of time is spent in the `parse_qs` function, which is implemented in regular python in stdlib. A C implementation would probably help speed the parse a fair amount.

For fun, I also tried running the albatross benchmark with uvloop. It makes a pretty difference for the "hello" benchmark, making albatross go 2x as fast, total of 4x faster than tornado/aiohttp without uvloop. It makes almost no difference for the "form" benchmark, again because time is dwarfed by the parse_qs implementation.

uvloop also seems to have some kind of bug in it, as when I used uvloop, I got a HTTP parsing error in albatross of the following form:

```
Traceback (most recent call last):
  File "/workspace/albatross/albatross/server.py", line 137, in _handle
    req, handler = await self._parse_request(request_reader, response_writer)
  File "/workspace/albatross/albatross/server.py", line 69, in _parse_request
    method, url_string, _ = request_line.split(' ', 2)
ValueError: not enough values to unpack (expected 3, got 1)
```
